name: cabal-prettify --check --this
on:
  workflow_run:
    workflows:
      - Haskell-CI
    types:
      - completed
jobs:
  check:
    name: cabal-prettify --check --this
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cabal/store
          restore-keys: ${{ runner.os }}-
      - run: cabal run cabal-prettify -- --check --this
      - run: false
